### ISSUE TITLE
Not able to create an account

### ISSUE THREAD

**Issue by godbout** [MuShare/Httper-iOS#11]
I want to sync my projects, but creating an account never works. Getting a dialog titled "tip" saying there's an "unknown error". Tried different password combination but it didn't change anything.

Any log I can provide to help diagnose?

**Comment by lm2343635** [comment]
Thank your for your replying.
I found this error too. I will fix it this week.

**Comment by godbout** [comment]
Still not working 😊️ 😘️

**Comment by lm2343635** [comment]
I am sorry that I am busy this month. 
But now I have solved this problem(caused by HTTPS) and submit a new version on App Store.
Best wishes.

**Comment by godbout** [comment]
😍️
Thanks!

**Comment by lm2343635** [comment]
New version has been updated!

**Comment by godbout** [comment]
Yep, already signed up! Thanks a lot, very useful piece of app :)
