### ISSUE TITLE
Ability to copy/cut/paste/search or inspect request output

### ISSUE THREAD

**Issue by javadahmadzadeh** [MuShare/Httper-iOS#14]
It would be nice if I can search in the output section (very useful for huge ones), play with it, collapse and expand it and finally Copy/Cut/Paste the data within the app. Also if I can export the output to file or share it via 3rd parties.

**Comment by lm2343635** [comment]
Due to the framework I used now, it difficult to implement such functions now.
I will try it when I am free.
Thank you for using Httper.

**Comment by lm2343635** [comment]
Copy/Cut/Paste is supported in PR #21 .
