### ISSUE TITLE
Crash on iPhone 7 when "Save to Project" on iOS 12 (Beta)

### ISSUE THREAD

**Issue by DaMo86** [MuShare/Httper-iOS#26]
The app just crashes (app window is closed and does not show up in open apps) when I try to save a request to a new and empty project. The request is not saved when I check after restarting the app.
I am using iOS 12 Beta.

**Comment by lm2343635** [comment]
Thank you for your replying!
I'll confirm this issue.

**Comment by lm2343635** [comment]
There are many issues and bug in this app. I am considering to refactor it using MVVM.

**Comment by lm2343635** [comment]
App Store version 2.6.1 updated.
https://github.com/MuShare/Httper-iOS/releases/tag/2.6.1
