### ISSUE TITLE
升级至ios 3.0.1出现的三个问题

### ISSUE THREAD

**Issue by debugbb** [MuShare/Httper-iOS#36]
设备：iPhone7；应用版本：3.0.1；ios版本：10.3.3
1、request method选择框消失，不知是否是布局问题；
2、下方save to project和send request按钮遮挡；
3、保存至project的请求，url会被截到只剩ip
ps：附图一张
![微信图片_20190626112706](https://user-images.githubusercontent.com/6327466/60149127-3fda2f00-9806-11e9-88d4-a5d10ce25c13.jpg)

**Comment by lm2343635** [comment]
哦哦，这个是iOS 10的布局问题，之后有时间修复哈。

**Comment by lm2343635** [comment]
3.0重构之后用SnapKit纯手工布局，因为涉及到auto layout的问题。
本来想着开发者都会升级到最新的系统，直接把最低版本号调整到11的。。。

**Comment by debugbb** [comment]
是的，感谢回复，忘记报ios系统了~~~，老设备没升级，伤不起啊

**Comment by lm2343635** [comment]
iOS 10还有其他问题，但是都很不好搞了，主页修复后暂时能用了。
其他的以后再说吧，13都要发了，以后不打算支持10了。
@debugbb 

![Screen Shot 2019-06-26 at 18 43 48](https://user-images.githubusercontent.com/9463655/60169780-569e7700-9842-11e9-9931-5b81a425ac80.png)
![Screen Shot 2019-06-26 at 18 43 57](https://user-images.githubusercontent.com/9463655/60169797-5c945800-9842-11e9-877f-6564cc007029.png)
![Screen Shot 2019-06-26 at 18 44 04](https://user-images.githubusercontent.com/9463655/60169806-61590c00-9842-11e9-81a6-d7002ff9002e.png)

**Comment by debugbb** [comment]
收到更新

**Comment by debugbb** [comment]
收到更新！

**Comment by lm2343635** [comment]
麻烦2星改个5星好评呗 😁

**Comment by lm2343635** [comment]
还有其他UI之后慢慢改

**Comment by debugbb** [comment]
汗，当时手滑了点错了，后来发现能改，已改了

**Comment by debugbb** [comment]
URL截取得问题，盼修改，谢谢

**Comment by lm2343635** [comment]
URL截取问题截个图 再开个issue。我有点不明白
