### ISSUE TITLE
ios10升级至3.0.2的问题：保存至project中的请求，再打开时出现url截取

### ISSUE THREAD

**Issue by debugbb** [MuShare/Httper-iOS#38]
设备：iPhone7；应用版本：3.0.2；ios版本：10.3.3
保存至project中的请求，再打开时出现url截取，截图如下：

![12121](https://user-images.githubusercontent.com/6327466/60317937-acd6fb80-99a3-11e9-9081-b28fed02f806.png)

**Comment by debugbb** [comment]
因为截图中的请求是之前保存的，刚才又试了下，新保存的请求，也是会如图中一样，出现截取情况

**Comment by lm2343635** [comment]
我在10.3模拟器里试了下，没有这个问题啊~

<img width="385" alt="Screen Shot 2019-06-28 at 22 22 20" src="https://user-images.githubusercontent.com/9463655/60345106-33ff9000-99f3-11e9-87b7-16d962ce6578.png">

<img width="385" alt="Screen Shot 2019-06-28 at 22 22 34" src="https://user-images.githubusercontent.com/9463655/60345115-3bbf3480-99f3-11e9-86ac-fc74ca21cfb6.png">

**Comment by lm2343635** [comment]
找到了，端口也是":"，应该用"://"做分隔符。

**Comment by debugbb** [comment]
对的，带端口号，已升级，修复啦，谢谢
