### ISSUE TITLE
Add double quote character to contextual keyboard

### ISSUE THREAD

**Issue by Jack-Barry** [MuShare/Httper-iOS#47]
When typing in a JSON request body, the iOS keyboard does not include the proper double quote character. (`"` vs. `“` and `”`) Would you be able to add the proper character into the contextual keyboard? The only way I can send a correctly formatted JSON request is to copy and paste it in.

Thanks!

**Comment by lm2343635** [comment]
You want to input the JSON string smartly.

**Comment by Jack-Barry** [comment]
@lm2343635 Not sure I follow - is that a setting somewhere in the app? 

When I input the request body the keyboard uses `“` and `”` instead of `"` which is the source of trouble.

I did find the way to change the contextual keyboard to have custom special characters so that will probably solve my issue, but I'm still not sure what you meant by input the JSON string smartly?

**Comment by lm2343635** [comment]
English keyboard is required to input `"`??
