### ISSUE TITLE
Can not edit parameters or headers on iPadOS

### ISSUE THREAD

**Issue by sebtomasi** [MuShare/Httper-iOS#78]
iPadOS : 14.2 (18B92)
Httper version:  3.4

I can’t edit the field for key and value, in the section Parameters or in Headers. I’ve tried on several iPads with different os.
The body section can be edited without any problem.

What can we do?

**Comment by lm2343635** [comment]
I am sorry that I did not understand what you said, I've tried on my iPad and it works well.
![IMG_7F4B91813FE8-1](https://user-images.githubusercontent.com/9463655/99779083-e5a6e000-2b57-11eb-977b-6cb7b9fa4bfd.jpeg)
Can you provide a screenshoot or a video?
You can send the video to httper@mushare.cn if the file is large.

**Comment by sebtomasi** [comment]
Actueally it doesn't work on the header part and the parameters part, i've to use the tab on the keyboard, because it doesn't work when i select key with the finger.

Please find attached a video

[HTTPER.mov.zip](https://github.com/MuShare/Httper-iOS/files/5610936/HTTPER.mov.zip)

**Comment by lm2343635** [comment]
Thanks, I will confirm it.

**Comment by lm2343635** [comment]
@sebtomasi 
Fixed, I will update it in version 3.4.4

**Comment by lm2343635** [comment]
@sebtomasi 
3.4.4 release, please confirm, thanks.

**Comment by sebtomasi** [comment]
@lm2343635, i've tested, it works great, thanks you very much, it's a great application
