### ISSUE TITLE
Potential Bug: Raw Request Body

### ISSUE THREAD

**Issue by httpuser** [MuShare/Httper-iOS#8]
Great app. I am running into an issue when I selected the “Raw Request Body” function, the app crashes. Working from both an iPhone 7 and iPad Pro. Can you recreate on your device?

**Comment by lm2343635** [comment]
askari01 has fixed your problem, I will release it in the version 2.2.2 today.
Thanks.

**Comment by askari01** [comment]
the issue should be closed if new built is available on itunesconnect and in consent with the @httpuser
