### ISSUE TITLE
Potential Issue: parameter sent “string/string” returns “string\/string” when interacting with app authorization server

### ISSUE THREAD

**Issue by httpuser** [MuShare/Httper-iOS#9]
This is one of the better HTTP apps on the App Store, so thank you for all the work you’ve done.

In my HTTP request, I request a parameter (called scope). The value I input into the app is “string/string” with a forward slash. The HTTP call is successful, but what returns is “string\/string” - that is, a backslash must be getting added to the request from the application. Given my authorization server recognizes “string/string”, and not “string\/string”, the remainder of my workflow fails. 

Request
Key: scope
Value: string/string

Response
Value: scope string\/string

Any chance your app is adding a backslash upon sending the request? I tested this on a desktop with Postman to see if it was occurring there - appears it’s isolated to the Httper app.

Many thanks for checking this out.

**Comment by httpuser** [comment]
Correction - The authorization server appears to be returning the “\/“, and also serving up another token that has the correct format of “/“. Doesn’t appear to be an issue with your app. Closing this.

**Comment by lm2343635** [comment]
Are you Adam Crown?
